library(shiny)
library(DT)
library(data.table)
library(ggplot2)
library(shinydashboard)
library(readr)
library(dplyr)
library("readxl")
library("RColorBrewer")
library(rsconnect)
library(base)
library(datasets)
library(graphics)
library(grDevices)
library(methods)
library(readr)
library(readxl)
library(RColorBrewer)
library(stats)
library(utils)
library(sf)
library(writexl)
library(base64enc)
library(maps)
library(rgdal)
library(maptools)
library(sf)
library(cowplot)
library(googleway)
library(ggrepel)
library(ggspatial)
#COVID Section Data Files
Coviddata <- read_excel("ScotlandCase.xlsx")
VaccineData <- read_excel("ScotlandVaccine.xlsx")
Vaccine2nddose <- read_excel("Vaccine2nddoseScotland.xlsx")
Casesgendertotal <- read_excel("casesbygender.xlsx")
CasesAgeTotal <-read_excel("COVIDagegroups.xlsx")
CasesDeprivation <-read_excel("covidcasesdeprivation.xlsx")
CovidDeathsDeprivation <-read_excel("deaths deprivation.xlsx")
Covidtesting <-read_excel("testing.xlsx")
Covidtestingbig <-read_excel("scotlandtestingdatatable.xlsx")
COVIDHospital <-read_excel("hospitalstats.xlsx")
COVIDVaccine <-read_excel("vaccinescotlanddata.xlsx")
#Unintentional Injuries Data Files RTAS
admissionsRTAage <-read_excel("RTAagescotland.xlsx")
admissionsRTAgender <-read_excel("genderRTA.xlsx")
admissionsRTAmaleage <-read_excel("malertaage.xlsx")
admissionsRTAfemaleage <-read_excel("femalertaage.xlsx")
#Unitentional Injuries Data Files Falls
fallslocation <-read_excel("Falls Location of Injury.xlsx")
agefalls <-read_excel("Age Groups Falls.xlsx")
genderfalls <-read_excel("Gender Data Falls.xlsx")
#Unintentional Injuries Deaths Data Files
Injuriesagedeaths <-read_excel("Age Injuries Deaths.xlsx")
Injurieslocations <-read_excel("InjuryTypeDeaths.xlsx")
#SIMD Map
#Healthboards <- st_read("SG_SIMD_2020.shp")
#plot(Healthboards$geometry)